// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAyMQDPmsj4AAU2mMAZ7xa8TKd3JXJbKbs',
    appId: '1:105080072689:android:d5804a14916d96e8237c50',
    messagingSenderId: '105080072689',
    projectId: 'jobacceptancesystem-cf19d',
    storageBucket: 'jobacceptancesystem-cf19d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNQ-hxvqK38Lm0ATXPFsmd5ygNQkrP1wQ',
    appId: '1:105080072689:ios:b0038fdd4e0d0757237c50',
    messagingSenderId: '105080072689',
    projectId: 'jobacceptancesystem-cf19d',
    storageBucket: 'jobacceptancesystem-cf19d.appspot.com',
    iosBundleId: 'com.example.jobAcceptanceSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAa6NWCGF7LibMD84XtKIW4eit4L8Ombeg',
    appId: '1:105080072689:web:56d97f3c4ec25901237c50',
    messagingSenderId: '105080072689',
    projectId: 'jobacceptancesystem-cf19d',
    authDomain: 'jobacceptancesystem-cf19d.firebaseapp.com',
    storageBucket: 'jobacceptancesystem-cf19d.appspot.com',
    measurementId: 'G-LFJYM6FVLQ',
  );
}
